version: '3.1'

services:

  testdb:
    build: ./db
    ports:
      - 1234:5432
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: admin

  app:
    build: .
    ports:
      - 4321:5000
    volumes:
      - ./app:/app
    depends_on:
      - testdb
    command: ["/app/start.sh", "testdb"]
