version: '3.1'

services:

  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: admin

  app:
    build: .
    ports:
      - 80:5000
    volumes:
      - ./app:/app
    depends_on:
      - db
    command: ["/app/start.sh", "db"]
